general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 9

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[window]
decorations = "None"
padding.x = 14
padding.y = 14
opacity = 0.4
blur = true

[keyboard]
bindings = [
{ key = "Insert", mods = "Control", action = "Copy" },
{ key = "Insert", mods = "Shift", action = "Paste" }
]
